version: "3"

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "3532:5432"

  cache:
    image: redis:6-alpine
    ports:
      - "3579:6379"

networks:
  default:
