version: "3"

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "3532:5432"

  cache:
    image: redis:6-alpine
    ports:
      - "3579:6379"

  jaeger:
    image: jaegertracing/all-in-one:1.34
    ports:
      - "3531:6831/udp"
      - "3586:16686"

networks:
  default:
