"""add discord link

Revision ID: 61e85ed118c0
Revises: fee0fd5b1965
Create Date: 2022-05-21 01:12:15.985879

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "61e85ed118c0"
down_revision = "fee0fd5b1965"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("discriminator", sa.String(length=4), nullable=False),
        sa.Column("avatar", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("links")
    # ### end Alembic commands ###
